### ISSUE TITLE
wellrates values are different from summary file

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-autodiff#119]
Hi,
I want to calculate watercut from sim_fibo_ad's output, but I found the values in wellrates/ are totally different from that in summary file and restart file, which one should I believe now？

**Comment by atgeirr** [comment]
I have now checked this, and verified that the output is as expected (at least for spe3). Be aware that we no longer output the ascii output in wellrates/ (and others) by default, I was bitten by this at first as I was comparing new results in summary to old results in wellrates.

Closing this as fixed.
