### ISSUE TITLE
Error in well handling

### ISSUE THREAD

**Issue by osae** [OPM/opm-autodiff#143]
Norne: Starting out with 3 wells and a total of 18 completion intervals.  In the fourth step a new well with 9 intervals is opened and we get the following problem:
Program threw an exception: 
opm-autodiff/opm/autodiff/WellDensitySegmented.cpp:51
Here np:3  nw:4  nperf:27 and wstate.perfPhaseRates().size():54
Thus wstate seems to be out of sync with reality ...

**Comment by atgeirr** [comment]
This is now properly handled, closing.
