### ISSUE TITLE
Control mode switching for wells

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-autodiff#178]
Currently, the control mode of wells seems to be switched after each iteration of the Newton-Raphson solver. This is unphysical because the non-converged solutions which are seen by the non-linear solver do not need to exhibit any correlation with physical reality and can actually assume values which are far away from anything which is physically possible (e.g., pressures or saturations can be negative for such interim solutions). Thus, no control decision should be made based on such values and the control mode for wells should only be switched at the beginning of each time step.

If I understood something wrong, I'm happy to be corrected...

**Comment by atgeirr** [comment]
Marking this issue as a question and closing it. Then finer points of the Newton-like solution method, and especially the well controls are worthy of a discussion, but our current approach works well and so this is no problem or issue as such.
