### ISSUE TITLE
Move functionality from Opm::UgGridHelpers to opm-core/dune-cornerpoint

### ISSUE THREAD

**Issue by blattms** [OPM/opm-autodiff#192]
Those functions (at least if they do not require Eigen) should be of interest outside of opm-autodiff.
Therefore the funcions for Ug should be moved to opm-core and the ones for CpGrid to dune-cornerpoint.

That way the free function interface within UgGridHelpers should become more clear and more usable.

**Comment by atgeirr** [comment]
This move was accomplished in the fall, closing the issue.
