### ISSUE TITLE
Purpose of Duplicate PVT Region Index in BlackoilPropertiesADFromDeck

### ISSUE THREAD

**Issue by bska** [OPM/opm-autodiff#202]
Class `BlackoilPropsAdFromDeck` has members
```C++
std::vector<int> cellPvtRegionIdx_;
std::vector<int> pvtTableIdx_;
```
the contents of which are set in `BlackoilPropsAdFromDeck::init<>()` as
```C++
// ...
extractPvtTableIndex(cellPvtRegionIdx_, deck, number_of_cells, global_cell);
// ...
Opm::extractPvtTableIndex(pvtTableIdx_,
                          deck,
                          number_of_cells,
                          global_cell);
```
Name-space qualification aside, the input parameters to function `extractPvtTableIndex()` (i.e., `deck`, `number_of_cells`, and `global_cell`) are exactly the same in both cases so by construction the region vectors `cellPvtRegionIdx_` and `pvtTableIdx_` contain the same values and thus define the same cell-to-region mapping.

At present, `cellPvtRegionIdx_` is used to index into the surface condition density table `densities_`, (method `surfaceDensity()`) and as the return value of public method `cellPvtRegionIndex()` while `pvtTableIdx_` is used for "everything else".  The mapping vectors were both introduced in commit 756de358 (PR #131) as part of the work to introduce support for multiple PVT regions.

Neither the commit log nor the PR discussion explained this (and I clearly didn't pay enough attention to details in the review--mea culpa) so I'm asking after the fact: Why do we need both mapping objects?  Just for the record: The accompanying comments don't justify the existence of both members.

**Comment by atgeirr** [comment]
This turned out to actually be indicative of a problem, but was fixed in #320.
