### ISSUE TITLE
MULTREGT

### ISSUE THREAD

**Issue by totto82** [OPM/opm-autodiff#222]
Eclipse and OPM does not agree on the trans multipliers when MULTREGT is applied on the Norne deck. I don't see that MULTREGT is tested in test_transmissibilitymultipliers. I guess that's a good starting point for debugging this. 

@andlaus Can you do this? I guess you are the one that know this part of the code best.

**Comment by atgeirr** [comment]
Is this issue resolved? I would assume so, but would like the people who worked on this to confirm it.

**Comment by andlaus** [comment]
pending no bugs which evaded @totto82's and my testing, this should have been resolved about three months ago...
