### ISSUE TITLE
Pimpl in SimulatorFullyImplicitBlackoil<T> should be removed.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-autodiff#279]
IMHO it does not make any sense, as `SimulatorFullyImplicitBlackoil_impl.hh` is included in the header anyway. BTW: It did make sense before my change of adding a template parameter.

Maybe we should get rid of it?

**Comment by atgeirr** [comment]
It depends on what we think is likely for the future of this class. Is there a possibility that it will be un-templated? If not, I'm fine with removing the pimpl pattern. However, if a parallel simulator is realised using CpGrid and its single-core performance is just as good as with UnstructuredGrid, we may avoid the template usage and just go with CpGrid.

**Comment by dr-robertk** [comment]
Is this still a valid issue or can we close this?

**Comment by atgeirr** [comment]
This has actually been done: now SimulatorBase is a template (with the actual simulator that contains model-specific code as its template argument) and it is no longer possible to see a way to un-templify this short of a full redesign. The pimpl was removed in the process.
