### ISSUE TITLE
Make dune-istl dependency explicit.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-autodiff#295]
I am not sure whether it is wise to ask this and make everybody aware of it, but anyway:

We have seem to already have  a depdency on dune-istl in opm-autodiff. At least I would assume that the current master does not compile without it.

Maybe we should make this dependcy explicite by listing it in dune.module as a requirement?

**Comment by atgeirr** [comment]
That sounds right to me.

**Comment by blattms** [comment]
Just created a PR for this

**Comment by blattms** [comment]
closed with merging of #296 an #299
