### ISSUE TITLE
SPE9 stops after 22 time steps

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-autodiff#305]
with the current master versions of opm-{data,parser,core,autodiff} I get the following

```
and@heuristix:~/src/opm-autodiff|master > ./bin/sim_fibo_ad deck_filename=../opm-data/spe9/SPE9.DATA
[...]
---------------    Simulation step number 22    ---------------
      Current time (days)     385
      Current stepsize (days) 15
      Total time (days)       900


Iter    MB(OIL)  MB(WATER)    MB(GAS)       CNVW       CNVO       CNVG  WELL-FLOW WELL-CNTRL
   0  5.353e-05  1.081e-03  2.490e-03  4.069e-02  4.850e-01  7.007e-01  5.416e-01  0.000e+00
   1  2.311e-05  1.578e-05  1.546e-03  3.035e-01  1.482e-01  1.215e+01  2.024e+01  1.301e-18
   2  1.709e-05  1.758e-06  4.423e-04  4.867e-01  5.175e-02  5.851e+00  5.927e+00  0.000e+00
Switching control mode for well PROD17 from SURFACE_RATE to BHP
   3  9.675e-05  7.124e-05  1.169e-03  2.552e+00  8.655e+00  4.886e+01  1.415e+01  0.000e+00
Switching control mode for well PROD17 from BHP to SURFACE_RATE
   4  1.243e-05  4.964e-05  4.927e-04  1.803e+00  7.834e-01  1.816e+01  6.534e+00  0.000e+00
   5  5.221e-06  1.230e-05  7.576e-05  1.896e+00  1.160e+00  3.250e+00  9.739e-01  0.000e+00
   6  1.010e-06  3.377e-06  4.172e-05  2.097e+00  1.790e+00  2.012e+00  7.835e-01  0.000e+00
   7  6.719e-06  3.696e-06  4.387e-05  1.213e+00  4.289e-01  1.264e+00  5.546e-02  0.000e+00
   8  5.423e-08  1.017e-08  2.537e-05  4.297e-02  4.320e-02  2.737e-01  9.780e-02  0.000e+00
   9  7.132e-05  5.323e-06  5.958e-03  1.472e+00  1.038e-01  1.125e+02  7.771e+01  0.000e+00
Switching control mode for well PROD17 from SURFACE_RATE to BHP
  10  2.933e-04  1.492e-05  3.754e-03  6.202e+00  1.149e-01  7.709e+01  4.882e+01  0.000e+00
  11  5.038e-05  1.605e-05  1.066e-03  1.268e+00  3.931e-01  2.153e+01  1.369e+01  0.000e+00
Switching control mode for well PROD17 from BHP to SURFACE_RATE
  12  2.263e-06  1.247e-05  6.393e-04  2.504e-01  7.858e-01  9.825e+00  9.036e+00  0.000e+00
  13  7.350e-06  2.540e-06  1.421e-04  1.725e-01  4.428e-01  2.598e+01  1.880e+00  0.000e+00
 Oscillating behavior detected: Relaxation set to 0.9
  14  1.022e-06  4.442e-07  1.601e-05  5.401e-02  1.080e-01  8.686e+00  2.080e-01  0.000e+00
  15  1.169e-07  2.579e-07  7.043e-07  2.620e-02  1.381e-02  1.719e+00  2.039e-02  0.000e+00
Program threw an exception: [/home/and/src/opm-autodiff/opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp:340] Failed to compute converged solution in 15 iterations.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [/home/and/src/opm-autodiff/opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp:340] Failed to compute converged solution in 15 iterations.
Aborted
```

I assumed this has been fixed recently?! My compiler is CLang 3.5.0 with optimizations enabled.

**Comment by GitPaean** [comment]
Just something added. 

I feel like the program just terminated after failing in getting converged within 15 steps is a little too much. I am not sure if our time-stepper support cutting time step size automatically now. 

And also yesterday when I tried sim_fibo_ad.  I added the "max_iter = 100" in the param file, while sim_fibo_ad could catch it. I think similar things are happening to a lot of the parameters listed below. 

dp_max_rel found at /, value is '0.2'.
ds_max found at /, value is '0.05'.
dr_max_rel not found. Using default value '1e+09'.
relax_max not found. Using default value '0.5'.
max_iter not found. Using default value '15'.
max_residual_allowed not found. Using default value '1.79769e+308'.
relax_type not found. Using default value 'dampen'.
timestep.adaptive not found. Using default value 'false'.

**Comment by GitPaean** [comment]
Sorry. I just noticed the spaces besides the "=" when I posted the message. I just took back my comments.

**Comment by andlaus** [comment]
> And also yesterday when I tried sim_fibo_ad. I added the "max_iter = 100" in the param file, while sim_fibo_ad could catch it. I think similar things are happening to a lot of the parameters listed below. 

okay, I'll test it with these settings. But I think it should be able to converge just fine using the default parameters, right?

**Comment by andlaus** [comment]
ok, with `max_iter = 100` it runs through, but I think this is a pretty sub-optimal work-around...

**Comment by dr-robertk** [comment]
This has been an issue since two month now. max_iter=25 is enough though.

**Comment by atgeirr** [comment]
I did not see this problem because I used to run SPE9 with the following options:
```
dp_max_rel=0.2
dr_max_rel=0.2
ds_max=0.05
```
Then it all works fine. This was added a long time ago (to first get it up and running), and I am surprised if we at some point were able to run without these parameters, as it seems to me you are saying @dr-robertk.

We may want to use these strict parameters by default to have SPE9 run out of the box, but that may impose a severe disadvantage in terms of convergence rates (number of nonlinear iterations expected to increase), so it may be a better alternative to enable adaptive timestepping by default.

**Comment by andlaus** [comment]
> This has been an issue since two month now. max_iter=25 is enough though. 

I can confirm that it ran through using default parameters a while ago. (as @dr-robertk saysm it was about one to two months ago, but I also don't remember the exact date...)

on the other hand, this issue might have been caused by "numerical jitter" because even currently it is "almost" converged after 15 iterations...

**Comment by atgeirr** [comment]
This is no longer an issue, it runs through with default options now.
