### ISSUE TITLE
Bug in handling RESV conditions on injectors.

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-autodiff#307]
We currently get wrong results for the SPE1 test case. This is due to the simulator switching to injector RESV controls at the start (it should not), and then using that control for the rest of the simulation.

This happens because all calculations for RESV controls (in `SimulatorFullyImplicitBlackoil::Impl::computeRESV()`) are only done for producers, not injectors.

The bug was hidden earlier by a bug affecting the target value for this control, that has now been fixed.

**Comment by bska** [comment]
> This happens because all calculations for RESV controls [...] are only done for producers, not injectors.

Not so much bug as missing feature.  I was fully aware of the limitation when I implemented that component.

**Comment by atgeirr** [comment]
I will try to implement this feature then. I do not see any immediate difficulties, but that may just be me being naive and not looking for trouble closely enough.
