### ISSUE TITLE
compilation of flow_cp fails

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-autodiff#340]
on the latest master versions of dune, dune-cornerpoint, opm-core and opm-autodiff, I get the following error

```
In file included from /home/and/src/opm-autodiff/examples/flow_cp.cpp:69:
In file included from /home/and/src/opm-autodiff/opm/autodiff/SimulatorFullyImplicitBlackoil.hpp:109:
In file included from /home/and/src/opm-autodiff/opm/autodiff/SimulatorFullyImplicitBlackoil_impl.hpp:21:
/home/and/src/opm-autodiff/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp:252:69: error: no viable conversion from 'const Dune::CpGrid' to 'const UnstructuredGrid'
                                      Opm::UgGridHelpers::numCells( grid ),
```

I used CLang 3.5.0 for this.

**Comment by atgeirr** [comment]
I cannot reproduce this. It looks like somehow the grid helpers for CpGrid are not found. I do not understand why it works for me and not you, did you make a clean from-scratch build?

**Comment by andlaus** [comment]
> did you make a clean from-scratch build?

I `git reset --hard origin/master && git clean -fdx` the OPM modules before compiling.

Now I did the same with the dune modules and suddenly it works. weird. maybe I had a "half-compiled" dune-cornerpoint in my working copy...
