### ISSUE TITLE
Norne fails after 26 time steps with default parameters

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-autodiff#349]
This is on a machine using opensuse 13.2 and clang 3.5. it seems, like an exception is not caught where it is supposed to be:

```
./bin/flow deck_filename=../opm-data/norne/NORNE_ATW2013.DATA
[...]
---------------    Simulation step number 26    ---------------
      Current time (days)     329
      Current stepsize (days) 12
      Total time (days)       3312

PLT not supported, writing RFT data
PLT not supported, writing RFT data
PLT not supported, writing RFT data
PLT not supported, writing RFT data

Iter  MB(WATER)    MB(OIL)    MB(GAS)       CNVW       CNVO       CNVG  WELL-FLOW WELL-CNTRL
   0  1.752e-04  5.978e-04  1.941e-04  9.895e+00  3.094e-01  1.057e+01  1.173e+01  9.086e+00
Switching control mode for well C-1H from SURFACE_RATE to BHP
   1  7.777e-04  6.731e-07  1.541e-04  3.478e+01  1.381e-01  1.599e+01  2.295e+01  1.388e-17
   2  1.714e-04  1.008e-05  4.195e-04  6.871e+00  1.380e+02  1.423e+02  5.192e+01  6.939e-18
Switching control mode for well C-1H from BHP to SURFACE_RATE
   3  2.321e-04  2.068e-05  3.278e-04  1.019e+01  8.633e+01  3.525e+01  5.712e+01  6.939e-18
   4  4.818e-05  7.486e-06  2.357e-05  9.273e+00  3.071e+01  2.206e+01  8.594e-01  1.208e-13
   5  8.811e-06  1.550e-03  4.214e-02  5.901e+01  4.900e+03  3.078e+03  6.161e-02  8.882e-15
   6  6.489e-04  5.842e-02  4.525e-02  8.445e+01  1.243e+06  1.392e+04  1.999e+03  7.656e-13
   7  4.267e-04  6.048e+01  5.110e+03  8.570e+01  2.516e+09  6.854e+13  5.226e+01  3.713e-13
Switching control mode for well C-1H from SURFACE_RATE to BHP
   8  2.052e+05  5.308e+11  3.002e+13  3.698e+11  8.376e+31  2.543e+27  4.459e+02  4.430e+02
Switching control mode for well D-1H from RESERVOIR_RATE to BHP
Switching control mode for well B-4H from RESERVOIR_RATE to BHP
Switching control mode for well C-1H from BHP to SURFACE_RATE
   9  3.982e+34  1.860e+38  3.555e+43  1.111e+39  9.059e+50 -8.210e+55  2.043e+38  2.135e+14
Program threw an exception: [/home/and/src/opm-autodiff/opm/autodiff/CPRPreconditioner.hpp:501] CPRPreconditioner failed to solve elliptic subsystem.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [/home/and/src/opm-autodiff/opm/autodiff/CPRPreconditioner.hpp:501] CPRPreconditioner failed to solve elliptic subsystem.
Aborted
```

**Comment by atgeirr** [comment]
I think the Norne case must be run with adaptive timestepping, and making that the default will resolve this. The adaptive timestepper catches this and retries with a smaller step.

For the non-adaptive timestepper I do not think there is much that can be done: obviously the residual is about to blow up, and I think that means the timestep is simply too long.

**Comment by andlaus** [comment]
> I think the Norne case must be run with adaptive timestepping, and making that the default will resolve this. The adaptive timestepper catches this and retries with a smaller step.

making the adaptive stepper the default is a good idea in my opinion. The only issue I currently have with it is that if it is not instructed otherwise, it should first try with the report step size as time step size and only reduce the step size upon encountering errors. (it seems like it currently divides the report step size by a constant factor before doing anything else...)

**Comment by atgeirr** [comment]
> it should first try with the report step size as time step size and only reduce the step size upon encountering errors. (it seems like it currently divides the report step size by a constant factor before doing anything else...)

I think it is a little more complicated: it tries to keep the number of linear iterations close to a target, so it should split a long report step if it thinks that will increase the number of iterations too much. But I agree that it should not subdivide report steps always, irrespective of situation.

**Comment by atgeirr** [comment]
I propose this is closed as a non-issue: we should not expect to be able to run Norne with arbitrary timesteps without the adaptive timestepping. Agree, @andlaus?

**Comment by atgeirr** [comment]
Closing this as fixed, since Norne now runs with default parameters (that turn on adaptive timestepping).
