### ISSUE TITLE
PRESSURE deviations increased on SPE cases

### ISSUE THREAD

**Issue by flikka** [OPM/opm-autodiff#367]
After https://github.com/OPM/opm-autodiff/pull/362, the checks that compares SGAS, SWAT and PRESSURE between a "fresh" run of the flow simulator on SPE cases started to "fail", see https://ci.opm-project.org/view/SPE%20Tests

To see some more details, go into a failing or succeeding "build", and the output of the runs and the comparison is shown. It appears that the PRESSURE values are the ones starting to deviate a bit more. Both compared to the Eclipse runs, and to the "reference" OPM runs.

I have verified locally, that when reverting to 78be86a9ed4ba8b7eefb8cf45f78ade4ffeb1f82 things are "back to how they were".

I don't know if this is important, but just pointing it out. Any recommendations to make the builds "green" again? One is of course to just increase the fault tolerance, but if there are other tweaks that might influence the results in a positive way, please let me know! Thanks.

**Comment by atgeirr** [comment]
Thanks for pointing this out. I think that the correct way to make these tests green again is to keep running them with the same parameters as before. They just are no longer the default parameters, so we should supply a parameter file with those parameters.

With the new defaults, time stepping becomes adaptive and therefore entirely different from before, so it is not strange that the tests complain.

**Comment by flikka** [comment]
Ok, thank you for the swift response! I'll try to update parameters in the input param files.

**Comment by atgeirr** [comment]
This has been fixed by @flikka I think, so I am closing the issue. Feel free to reopen if I was mistaken.
