### ISSUE TITLE
Problem using DuneMatrix with Dune::SeqILU0

### ISSUE THREAD

**Issue by TobiasRitschel** [OPM/opm-autodiff#383]
Hi

I want to solve a linear system using one of the iterative methods in Dune ISTL. I am using opm-autodiff to produce the system matrix which is then in the `Eigen::SparseMatrix<double>` format (or `AutoDiffBlock::M`). I am trying to define a preconditioner in the following way
```C++
Opm::DuneMatrix JacDune(residual.derivative()[0]);
Dune::SeqILU0<Opm::DuneMatrix, Dune::FieldVector<double,2*961>, Dune::FieldVector<double,2*961>> JacPrec(JacDune,0.);
```
When I compile, I get the following error
```
/home/tobias/Documents/petsc/arch-linux2-c-debug/bin/mpicxx -o src/OPMSim.o -c -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -g -O0  -fPIC   -std=c++11 -Wall -g -DNDEBUG -O1 -I/home/tobias/Documents/petsc/include -I/home/tobias/Documents/petsc/arch-linux2-c-debug/include    `pwd`/src/OPMSim.cpp
In file included from /usr/include/dune/common/fmatrix.hh:13:0,
                 from /usr/local/include/opm/autodiff/DuneMatrix.hpp:33,
                 from /home/tobias/Documents/OPM_Optimization/src/../header/OPMSim.hpp:3,
                 from /home/tobias/Documents/OPM_Optimization/src/OPMSim.cpp:2:
/usr/include/dune/common/densematrix.hh: In instantiation of \u2018void Dune::DenseMatrix<M>::mmv(const X&, Y&) const [with X = double; Y = double; MAT = Dune::FieldMatrix<double, 1, 1>]\u2019:
/usr/include/dune/istl/ilu.hh:110:9:   required from \u2018void Dune::bilu_backsolve(const M&, X&, const Y&) [with M = Opm::DuneMatrix; X = Dune::FieldVector<double, 1922>; Y = Dune::FieldVector<double, 1922>]\u2019
/usr/include/dune/istl/preconditioners.hh:536:29:   required from \u2018void Dune::SeqILU0<M, X, Y, l>::apply(X&, const Y&) [with M = Opm::DuneMatrix; X = Dune::FieldVector<double, 1922>; Y = Dune::FieldVector<double, 1922>; int l = 1]\u2019
/home/tobias/Documents/OPM_Optimization/src/OPMSim.cpp:395:1:   required from here
/usr/include/dune/common/densematrix.hh:486:36: error: subscripted value is neither array nor pointer
           y[i] -= (*this)[i][j] * x[j];
                                    ^
/usr/include/dune/common/densematrix.hh:486:12: error: subscripted value is neither array nor pointer
           y[i] -= (*this)[i][j] * x[j];
            ^
/usr/include/dune/common/densematrix.hh: In instantiation of \u2018void Dune::DenseMatrix<M>::umv(const X&, Y&) const [with X = double; Y = double; MAT = Dune::FieldMatrix<double, 1, 1>]\u2019:
/usr/include/dune/istl/ilu.hh:123:7:   required from \u2018void Dune::bilu_backsolve(const M&, X&, const Y&) [with M = Opm::DuneMatrix; X = Dune::FieldVector<double, 1922>; Y = Dune::FieldVector<double, 1922>]\u2019
/usr/include/dune/istl/preconditioners.hh:536:29:   required from \u2018void Dune::SeqILU0<M, X, Y, l>::apply(X&, const Y&) [with M = Opm::DuneMatrix; X = Dune::FieldVector<double, 1922>; Y = Dune::FieldVector<double, 1922>; int l = 1]\u2019
/home/tobias/Documents/OPM_Optimization/src/OPMSim.cpp:395:1:   required from here
/usr/include/dune/common/densematrix.hh:445:36: error: subscripted value is neither array nor pointer
           y[i] += (*this)[i][j] * x[j];
                                    ^
/usr/include/dune/common/densematrix.hh:445:12: error: subscripted value is neither array nor pointer
           y[i] += (*this)[i][j] * x[j];
            ^
make: *** [src/OPMSim.o] Error 1
```
I'm a bit at a loss. I just started using the CMake build system and it might be that I did something wrong in the process. I copied the dune.module file, the cmake folder, CMakeLists.txt and CMakeLists_files.cmake and adjusted them. It produces the config file which I include as the first in my .cpp files. I then have a makefile that I created myself (is this misunderstood?), which I use to compile the code.

I wasn't sure whether to post the question here or at the Dune bugtracker but thought it was best here since it involves the DuneMatrix object.

Any help is much appreciated.

**Comment by blattms** [comment]
On Thu, May 21, 2015 at 09:52:06AM -0700, TobiasRitschel wrote:
> /usr/include/dune/common/densematrix.hh: In instantiation of \u2018void Dune::DenseMatrix<M>::mmv(const X&, Y&) const [with X = double; Y = double; MAT = Dune::FieldMatrix<double, 1, 1>]\u2019:
> /usr/include/dune/istl/ilu.hh:110:9:   required from \u2018void Dune::bilu_backsolve(const M&, X&, const Y&) [with M = Opm::DuneMatrix; X = Dune::FieldVector<double, 1922>; Y = Dune::FieldVector<double, 1922>]\u2019
> /usr/include/dune/istl/preconditioners.hh:536:29:   required from \u2018void Dune::SeqILU0<M, X, Y, l>::apply(X&, const Y&) [with M = Opm::DuneMatrix; X = Dune::FieldVector<double, 1922>; Y = Dune::FieldVector<double, 1922>; int l = 1]\u2019


This won't work as DuneMatrix is a sublcass of
BCRSMatrix<FieldMatrix<double,1,1> > which needs a
BlockVector<FieldVector<double,1>> as X and Y in the SeqILU0::apply.

Even if it would not, then I would assume that the size of the vectors
does depend on the problem. Whereas the size of the
FieldVector<double,1922> is constant for the whole binary no matter
what the problem size is. That is probably not what one wants.

**Comment by TobiasRitschel** [comment]
I believe that helps. Using 1922 was just to try to narrow down the problem, it's right that it should be problem dependent.

I now get the following error

src/OPMSim.o: In function `Dune::Exception::Exception()':
/usr/include/dune/common/exceptions.hh:182: undefined reference to `Dune::Exception::_hook'
collect2: error: ld returned 1 exit status
make: [oil] Error 1 (ignored)

**Comment by blattms** [comment]
Looks like it is not linked to libdunecommon. Could you check or post the linker line produced with ```make VERBOSE=1 oil``` just to be sure.

**Comment by TobiasRitschel** [comment]
It produces the following

-lopmautodiff -ldunecornerpoint -lopmcore -lParser -lopm-json -lanalysis -lconfig -lecl -lecl_well -lenkf -lert_geometry -lert_util -ljob_queue -llapack -lblas -lplot -lrms -lsched -lboost_regex -lboost_system -lboost_filesystem -lsuperlu -lumfpack -Wl,-rpath,/home/tobias/Documents/petsc/arch-linux2-c-debug/lib -L/home/tobias/Documents/petsc/arch-linux2-c-debug/lib  -lpetsc -Wl,-rpath,/home/tobias/Documents/petsc/arch-linux2-c-debug/lib -lf2clapack -lf2cblas -lm -lX11 -lpthread -lm -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -Wl,-rpath,/usr/local/lib/x86_64-linux-gnu -L/usr/local/lib/x86_64-linux-gnu -lmpichcxx -lstdc++ -Wl,-rpath,/home/tobias/Documents/petsc/arch-linux2-c-debug/lib -L/home/tobias/Documents/petsc/arch-linux2-c-debug/lib -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/local/lib/x86_64-linux-gnu -L/usr/local/lib/x86_64-linux-gnu -ldl -Wl,-rpath,/home/tobias/Documents/petsc/arch-linux2-c-debug/lib -lmpich -lopa -lmpl -lrt -lpthread -lgcc_s -ldl

I tried to add -ldunecommon to the libraries that I link with and the program then compiles.
