### ISSUE TITLE
Memory access error in BlackoilSolventModel

### ISSUE THREAD

**Issue by babrodtk** [OPM/opm-autodiff#452]
In `opm/autodiff/BlackoilSolventModel_impl.hpp:658`, there is a check
```C++
mass_balance_residual[Solvent]
```
yet `mass_balance_residual` is defined as
```C++
std::array<double,MaxNumPhases+1> mass_balance_residual
```
and `Solvent` is defined as 
```C++
CanonicalVariablePositions::Next = 5
```
The `mass_balance_residual` for `Solvent` is not computed either in the for loop just above.

**Comment by babrodtk** [comment]
This gives a warning,
```
opm/autodiff/BlackoilSolventModel_impl.hpp:655:9: warning: ‘*((void*)& CNV +40)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
```
when compiled with -Wmaybe-uninitialized, but there is also an out-of-bounds access here, since the array has size MaxNumPhases+1 = 4.

**Comment by totto82** [comment]
This is clearly a bug. I suggest to use mass_balance_residual[MaxNumPhases]

**Comment by atgeirr** [comment]
The time is ripe for refactoring these functions to have a single version that works for all of our current models instead of each of the providing their own copy, but I think it's ok to make a quick fix for this bug first.

**Comment by totto82** [comment]
Quick fix is on its way
