### ISSUE TITLE
initial condition of flow quite different from eclipse for "SPE1CASE1.DATA" 

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-autodiff#464]
`flow` initial condition:

![flow_spe1case1_initial](https://cloud.githubusercontent.com/assets/1837735/9715891/2c75b16a-5565-11e5-806d-88761b8beacd.png)

Eclipse initial condition:

![eclipse_spe1case1_initial](https://cloud.githubusercontent.com/assets/1837735/9715887/2465b5a6-5565-11e5-95f1-44276dc8911f.png)

as a consequence it is pretty hard to compare how these two simulations evolve. the difference seems to be caused by the EQUIL code. (the original SPE1 case initializes the deck explicitly via SGAS, PRESSURE, etc., so this issue does not apply to it.)

**Comment by atgeirr** [comment]
Is this still a problem @andlaus, or was it resolved?

**Comment by andlaus** [comment]
I'm not aware of any PRs related to this, but maybe it was resolved as a "drive-by". (I don't think so, though.)

**Comment by andlaus** [comment]
ok. I had a look again and it seems to be related to using STONE1. closing.
