### ISSUE TITLE
flow_cp struggles with Norne around day 820.

### ISSUE THREAD

**Issue by dr-robertk** [OPM/opm-autodiff#467]
When running Norne using flow_cp (serial) I can't get passed 820 days, which is no problem with flow. 
What could be different?

**Comment by GitPaean** [comment]
How did it stop there? Due to too many restarts?

**Comment by dr-robertk** [comment]
Yes, many restart and therefore tiny timesteps. Still no convergence. I would expect the results of flow and flow_cp to be at least similar.

**Comment by blattms** [comment]
I must admit that I did not compare flow and flow_cp lately. But I can
say that on my system I can run the full norne simulation with flow_cp
(using the default_norne.param with a slight modifaction
```diff
diff --git a/norne/norne_default.param b/norne/norne_default.param
index 60e73a0..920d7c5 100644
--- a/norne/norne_default.param
+++ b/norne/norne_default.param
@@ -32,7 +32,7 @@ cpr_solver_tol=0.01
 cpr_max_elliptic_iter=25
 // CPR preconditioner ILU version
 // relaxation parameter
-cpr_use_amg=true
+cpr_use_amg=false
 //////////////////////////////
 // TimeStepping
 ////////////////////////////////
@@ -54,3 +54,6 @@ solver.verbose=true
 solver.restart=10
 // factor by which the time step is reduced after the solver did not converge
 solver.restartfactor=0.3
+output=false
+output_matlab=false
+output_ecl=false
```

It also work with an parameter file that Alf gave me.

But that does not mean that does not struggle harder than flow.

**Comment by blattms** [comment]
I will try to replicate.
I am rephrasing @dr-robertk's question: What is different/special in simulation step 820 compared to the previous ones?

**Comment by GitPaean** [comment]
I am not sure about if day 820 has something obviously different. 

When I tried to work on some things to improve the iteration process, with some different parameters or strategies, it is easy to get stuck at some time steps (Not necessary day 820, for example Simulation step number 25   Current time (days)     326). From my observation, the iteration process is still a little unpredictable. Some tiny difference from the previous time steps can result in all kinds of problems later.

**Comment by blattms** [comment]
I did a run with flow_cp and flow. They do behave differently starting from step 1 (flow_cp 61 and flow 81 linear iterations). Next step flow_cp needs to use a smaller stepsize ...
Overall the performance on Norne is similar:

|                                          |flow_cp: | flow          |
----------------------------------------|--------------|--------------|
|Total time taken (seconds): | 2357.01 | 2335.5    |
|Solver time (seconds):         | 2353.27 | 2332.51  |
|Overall Newton Iterations:    | 1531     | 1522       |
|Overall Linear Iterations:      |23284    | 23628     |

As the ordering of the cells should be the same, I am unsure what is causing this. Maybe a different traversal of the cell neighbors leading to different round-off errors? The famous sparse matrix-sparse-matrix multiply leading to a different sparsity pattern....
Maybe someone should take a look at the results and compare.

**Comment by blattms** [comment]
@atgeirr wrote in OPM/dune-cornerpoint#168
> > Do UG and CpGrid even use the same centroid computation?

> No they don't, and small differences in centroids, areas and volumes could be a significant factor in why the results are different.

**Comment by dr-robertk** [comment]
This seems to be fixed.
