### ISSUE TITLE
Physically, what kind of wells will be considered to be not alive?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-autodiff#474]
From the code, it looks like if a well does not inject, and also no flow towards well-bore from reservoir happens, the well will be considered not alive. 

But in the actual simulation, what kind of set up will make a well not alive? Thanks.

**Comment by totto82** [comment]
For instance setting the injection rate to zero will as I understands it result in a not alive well. You may still have crossflow in a not alive well in cases where the total flow towards the well-bore from the reservoir equals the total flow out of the well-bore into the reservoir. For not alive wells the control equations will be trivial and special treatment is therefore needed.

**Comment by GitPaean** [comment]
The formulation is as follows, 
`(compi.col(pos) * injectingPhase_selector.select(q_s,ADB::constant(V::Zero(nw))))  - q_ps;  `

The first term only handles the `injecting phase`, which will be positive in values (`>=0`).  And the second term only handles `ProducingPerforations`, which means the flow towards the well-bore, and will be negative in values. 

It looks like if there are some flow towards the well-bore happen for a well, it will be an alive well. It does not matter if the sum of the in-flow and out-flow is `zero`. 

Please let me know if there some misunderstanding here.

**Comment by totto82** [comment]
You are right. The total wellbore volumetric rates (wbqt) consider the total inflow to the well-bore and is used to calculate the mixture of the fluids inside the wellbore. I.e. It means that a well is not alive if there is nothing flowing into it neither from the reservoir or from the top side.

**Comment by GitPaean** [comment]
Thanks.
