### ISSUE TITLE
flow cannot run old SPE9 deck anymore.

### ISSUE THREAD

**Issue by dr-robertk** [OPM/opm-autodiff#489]
I was trying to run the old SPE9 cases to verify some strange behavior with the new case, but it seems not to work anymore. I get the following output:
```
deck_filename found at /, value is SPE9.DATA
output not found. Using default value 'true'.
output_dir found at /, value is 'opm-simulation'.
Failed to create valid ECLIPSESTATE object. See logfile: opm-simulation/LOGFILE.txt
Exception caught: Missing item information CPR
```
When I look at the `LOGFILE.txt` as suggested: it's empty. So I have no clue what has changed. I this an opm-parser or an opm-autodiff issue?

Even though the old deck was removed I don't think that flow should all of a sudden not be able to simulate this anymore.

**Comment by joakim-hove** [comment]
Hmm - this a Parser issue, start by commenting out the CPR keyword from the
deck. Fix coming tomorrow.
21. sep. 2015 20:07 skrev "dr-robertk" <notifications@github.com> følgende:

**Comment by joakim-hove** [comment]
This is a result of: https://github.com/OPM/opm-parser/pull/581 We have added support for a `CPR` keyword; however from a cursory glance at the old deck it seems `CPR` can also occur in the summary section - will investigate further tomorrow.

**Comment by joakim-hove** [comment]
Could you give this a spin: https://github.com/OPM/opm-parser/pull/587

**Comment by dr-robertk** [comment]
This seems to be fixed in the current  master.
