### ISSUE TITLE
Should flow work on subgrids?

### ISSUE THREAD

**Issue by blattms** [OPM/opm-autodiff#490]
Lets say I have an eclipse deck, e.g. Norne, but set up a grid that only covers a part of the grid as defined in the deck. Should I be able to setup flow/flow_cp with this? If not I will not investigate more time in this.

Currently there  seem to be several issues in opm-core preventing this, some in the wells manager and some when initializing the simulator state.

**Comment by blattms** [comment]
Not relevant any more as my idea will not work anyway.

**Comment by bska** [comment]
> Not relevant any more as my idea will not work anyway.

Okay, but the answer to the original question is probably "no".  It would be nice to be able to run a simulator on a (connected) subset of the grid cells, but right now there are too many parts of the code that assume a global view of the model.
