### ISSUE TITLE
Why both fluidRsSat() and fluidRvSat() depend on the oil saturation?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-autodiff#501]
while no one depends on gas saturation? Could anyone give me a simple explanation or refer to some reference? Thanks.

**Comment by atgeirr** [comment]
I think this is due to the oil vaporization controls (VAPOIL) feature. @osae?

**Comment by osae** [comment]
That is essentially right.  The basic saturated (bubble point) values for Rs and Rv are functions of pressures only, but the VAPPARS (i.e. not VAPOIL) modification (for both Rs and Rv) relates the current oil saturation to a cached historical maximum for each grid cell.

**Comment by GitPaean** [comment]
Thanks for the responses. I will check the keyword when I get a chance later.
