### ISSUE TITLE
ParallelDebugOutput complains about missing well

### ISSUE THREAD

**Issue by blattms** [OPM/opm-autodiff#521]
When running Norne in parallel I get the following error in simulation step 3:
```
Program threw an exception: [/home/mblatt/src/dune/opm-amg-opt/opm-autodiff/opm/autodiff/ParallelDebugOutput.hpp:511] global state does not contain well D-2H
```
I have investigated this a bit. It seems like the wells are read from a wells manager initialized with an EclipseState for iteration 0. Which means that wells appearing later are neglected. I guess, the initialization has to be for the very last iteration step as well might appear but never disappear (they are shut instead).

**Comment by blattms** [comment]
I will try to fix this myself.

**Comment by blattms** [comment]
@dr-robertk Hopefully you do not check whether the master process receives data for each well it knows. Do you?

**Comment by blattms** [comment]
My supposed fix does not work as the well manager neglects shut wells and I no get the same error for the first timestep. I guess we either have to rewrite the code to work without the wells manager or reinitialize the wellmanger for each iteration step.
I am leaving this to the original author. He should be much quicker than me to fix this.

**Comment by dr-robertk** [comment]
I'll have a look.

**Comment by dr-robertk** [comment]
Could you be more specific about the parameters/versions used? I have pull all your pending PRs and run the full norne data set. Seems like I don't even get to step 3. 

Nevertheless, there are couple of options to fix this problem. 
I have proposed a fix that initializes the wells for each output step. Please see #522.

**Comment by blattms** [comment]
Closing as #522 got merged.
