### ISSUE TITLE
Why does SimulatorBase::computeResv use the EclipseState and not the WellsManager

### ISSUE THREAD

**Issue by blattms** [OPM/opm-autodiff#528]
During one of my many debugging sessions I realized the well code in OPM is even more scattered than I thought. I was under the impression that all the wells processing in opm-autodiff is uses the `WellsManager` from opm-core. All? No, like in Asterix there is an exception (which breaks the current parallelization, sigh):

In `SimulatorBas::computeResv`, see https://github.com/OPM/opm-autodiff/blob/a3d42244452229f50febd8671df149f91316ae07/opm/autodiff/SimulatorBase_impl.hpp#L356, it is not used but the wells information is (again!) extracted from the `EclipseState`. Is this an oversight or is a feature needed that is not available in the `WellsManager`?

I any case I consider this rather dangerous as the representation in the `WellsManager` might diverge from the well representation in `EclipseState` even in the sequential (for sure in the parallel case!). If I am not mistaken Shut wells are not represented in the `WellsManager` but are in the `EclipseState`.

**Comment by bska** [comment]
> Is this an oversight or is a feature needed that is not available in the WellsManager?

Using the `EclipseState` in `computeRESV` is definitely intentional.  The history controls, in particular, are not available in the `WellsManager`.  I'll say again that the `WellsManager` is a legacy interface that we should not build further features on top of.

**Comment by blattms** [comment]
Well, this is not yet in any sense reflected in opm-autodiff:
```sh
mblatt@boromir:~/src/dune/opm/opm-autodiff$ find . -name \*.[hc]pp | xargs grep WellsManager | cut -d: -f1| sort |uniq
./examples/flow.cpp
./examples/flow_solvent.cpp
./examples/opm_init_check.cpp
./examples/sim_2p_incomp_ad.cpp
./opm/autodiff/ParallelDebugOutput.hpp
./opm/autodiff/SimulatorBase.hpp
./opm/autodiff/SimulatorBase_impl.hpp
./opm/autodiff/SimulatorFullyImplicitBlackoilSolvent.hpp
./opm/autodiff/SimulatorFullyImplicitBlackoilSolvent_impl.hpp
./opm/autodiff/SimulatorIncompTwophaseAd.cpp
./opm/autodiff/SimulatorIncompTwophaseAd.hpp
```

**Comment by blattms** [comment]
At least I am in good company with my ignorance;) : @totto82 @babrodtk @joakim-hove have made changes to the WellsManager, too.

@bska: What is the plan? Always use the Eclipsestate and every time neglect shut wells or a new abstraction in opm-autodiff? 
In the latter case: Are you sure that no functionality of opm-core is called that expects a WellsManager?

**Comment by bska** [comment]
> Well, this is not yet in any sense reflected in opm-autodiff:

I know.  That's a long-standing bug in our implementation.  Besides, opinions differ on the matter but the `WellsManager` really is a lot less powerful than the `EclipseState` and were it not for the fact that the class fulfils the role of `std::shared_ptr<Wells>` in addition to its methods I would have moved for its removal long ago.

> What is the plan? Always use the Eclipsestate and every time neglect shut wells or a new abstraction in opm-autodiff?

I would definitely prefer that we shifted to using the `EclipseState` for **all** dynamically changing properties.  The well topology is a little less clear because it needs to match the active cells.

> Are you sure that no functionality of opm-core is called that expects a WellsManager?

Not at all.  We would need to review the code base to check.

**Comment by joakim-hove** [comment]
> At least I am in good company with my ignorance;) : @totto82 @babrodtk @joakim-hove have made changes to the WellsManager, too.

Yes - I have made changes to the `WellsManager` - but more so I have argued for killing it. When people realize how convoluted the well handling is they get upset - and then they eventually give up and decide to spend their efforts on other parts of the code.

This is my rough picture of the three object systems related to wells in flow:

1. Internalization of input - including all dynamic input properties and topology in `EclipseState`.
2. Copy a snapshot valid for *one timestep* of the dynamic well controls and the completed cells++ to `struct wells` and the `WellsManger`- which manages a `struct wells` pointer.
3. `WellState` which is closely tied to the simulator, and manages states variables which are solved for - and also some dynamic control copied from the `WellsManager`?

After the parsing is complete the `EclipseState::Schedule` object is immutable, and should be safe distribute read only copies to all processors in the process group; the `WellState` object can hopefully be simplified even further - and have shorter lifetime. I think we can gain quite a lot simplification (at least in the restart - and possibly also in MPI) if the `WellState`objects have their lifetime limited to the inner loop of the solver - possibly for the price of some "unnecessary" well state initialization code at the start of the solver iteration.

In my opinion there really is no space for `struct wells / WellsManager`.

**Comment by bska** [comment]
> In my opinion there really is no space for `struct wells` / `WellsManager`.

I agree with one provision (that I've mentioned repeatedly before but will state again for completeness).  If we can compute production indices that **exactly** match the set of active grid cells using `WellState` alone, i.e., there are no completions outside the grid's notion of active cells then the original well layer should just be replaced.

**Comment by joakim-hove** [comment]
>If we can compute production indices that exactly match the set of active grid cells using WellState alone

I do not see full ramifications of that provision - but I am quite confident that if we decide to it - we can do it.

**Comment by blattms** [comment]
@bska Thanks for the comment.
In contrast to what I assumed, this does not cause (the) problems, as the `struct Wells` is used to decide whether the wells in `EclipseState` are there. My problemstems from #530

**Comment by atgeirr** [comment]
I think the question has been answered, so I'll close it. I'll open an issue about the elimination of the WellsManager, referring to this discussion.
