### ISSUE TITLE
[MPI] SimulatorBase::rateConverter_ assumes a global grid.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-autodiff#530]
I computes averages of hydrogen pressures and temperatures in regions. (BTW: The region is hard coded in SimulatorBase as the whole grid) This does not work in parallel without any communication and result in wrong values being used in the wells model.

I am also a bit confused on the usage of `BlackoilPropsAdFromDeck::rsSat` which gets the temperature as a second parameter here while everywhere else the oil saturatio is used there. But this might just be due to my ignorance.

**Comment by blattms** [comment]
Concerning my confusion: As long as the eclipse key words VAPPAR, VAPOIL, and DISGAS are not used (seems to be the case in Norne) `BlackoilPropsADFromDeck::satOilMax_ will be empty and the saturation/temperature will be ignored. So for Norne we can pass in anything we want without side effects.

Concerning the region functionality: It is currently not used (region is always the whole grid). Can someone enlighten my how it would be used, namely how the regions would look like or be identified. Not having regions would make my life easier...

**Comment by bska** [comment]
This particular facility cares mostly about FIP regions (fluid in place) as identified by the FIPNUM keyword.

**Comment by atgeirr** [comment]
> VAPPAR, VAPOIL, and DISGAS are not used (seems to be the case in Norne)

These keywords are indeed used in Norne. Was that what you meant?

**Comment by blattms** [comment]
No I really meant what I was writing. But I agree that my assumption was wrong (just checked) and Norne uses all those keywords, indeed. 

Which brings up my original question: Why do we call `BlackoilPropsAdFromDeck::rsSat` with the temperature instead of the oil saturation at [RateConverter.hpp line 613](/OPM/opm-autodiff/blob/a3d42244452229f50febd8671df149f91316ae07/opm/autodiff/RateConverter.hpp#L613)

**Comment by bska** [comment]
Closing as solved in #531.
