### ISSUE TITLE
Convergence problems

### ISSUE THREAD

**Issue by totto82** [OPM/opm-autodiff#544]
With the current master I am not able to run the new model. I suspect #536, but I have not investigated it closely.

**Comment by atgeirr** [comment]
That is worrying, I find it hard to believe that #536 should be at fault though, the intention was at least to have the new approach behave identically. If that is at fault I must have made a mistake!

**Comment by atgeirr** [comment]
I have identified the causes of this, I think. Indeed #536 did change behaviour, it does not correctly respect the min_iter parameter.

However, the real cause of failure here is that the time stepping algorithm does not handle the situation arising when the solver used 0 steps! Is that the only reason why the min_iter parameter exists? If so, I'd rather fix this by removing that parameter and fixing the time stepping. If there are other gainful uses of it I'll fix min_iter in the NonlinearSolver as well.

**Comment by atgeirr** [comment]
I have now fixed the problem in #545 (not honoring min_iter), and created a new issue for the time stepper problem (#546).

**Comment by totto82** [comment]
Thanks
