### ISSUE TITLE
ert related crash

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-autodiff#571]
It happened a couple of times today.  When I run Norne, if the output (. or output, any directory you specify with output_dir) directory has the resulting output files from previous running (In my case, these running might not be finished and terminated by ctrl-c), sometimes the running were stopped right at the beginning of step 7 without giving any information. 

Running at debug mode, the following information was given. 
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6dd5259 in ecl_file_select_block () from /usr/local/lib/x86_64-linux-gnu/libecl.so.2
```
I am not sure if there anyone else also saw this.  
Anyone has some clues can give comments. 

I do not think it is a big problem at the moment. I will bring up this problem again when I can reproduce this problem for sure with a set up.

**Comment by bska** [comment]
Is there any chance you can get a back-trace and/or a core-file?  What's the exact command line you use to run the simulation case?

**Comment by joakim-hove** [comment]
> Running at debug mode, the following information was given.

OK - this is related to reading a binary file, would be very valuable if you knew which file it was. Backtrace?

**Comment by GitPaean** [comment]
> What's the exact command line you use to run the simulation case?
Just flow  DATA_FILE 

I will try to reproduce it and do a back-trace.

**Comment by dr-robertk** [comment]
I had the exact same problem but for some reason it went away when I
recompiled everything with the newest version. I did not investigate it
further.

**Comment by GitPaean** [comment]
I did not manage to reproduce the crash. It looks like related to the messy output files from running many times. And most likely related to the RBF file writing. I do not know why `timestep 7` is special here. 

Another crash happen with the following .param file. It happened when you have results output with `flow  NORNE_ATW2013.DATA` and `flow run.param` in the same folder. It happened several times, while I do not think it is something worth further investigation. I just put the information here for possible future reference. I will close this issue now. 
```
  1 deck_filename=NORNE_ATW2013.DATA
  2 output_dir=OPM
  3 use_interleaved=true
  4 full_timestep_initially=true
  5 solve_welleq_initially=true
  6 solver.restartfactor=0.5
  7 solver.growthfactor=2.
  8 timestep.control.targetiteration=150
```
And the backtrace is 
```
---------------    Simulation step number 7    ---------------
      Current time (days)     143
      Current stepsize (days) 1
      Total time (days)       3312



Abort called from: __hash_get_node_unlocked (/home/kaib/OPM/ert/devel/libert_util/src/hash.c:146) 

Error message: __hash_get_node_unlocked: tried to get from key:DEPTH which does not exist - aborting 



--------------------------------------------------------------------------------
 #00 util_abort__(..)                                                    in ???
 #01 hash_get(..)                                                        in ???
 #02 ecl_file_iget_named_kw(..)                                          in ???
 #03 ecl_rft_node_alloc(..)                                              in ???
 #04 ecl_rft_file_alloc(..)                                              in ???
 #05 ecl_rft_file_update(..)                                             in ???
 #06 _ZN3Opm20EclipseWriterDetails22EclipseWriteRFTHandler13writeTimeStepERKSs17ert_ecl_unit_enumRKNS_23SimulatorTimerInterfaceERSt6vectorISt10shared_ptrIKNS_4WellEESaISC_EES9_IKNS_11EclipseGridEERS8_IdSaIdEESL_SL_(..)    in /home/kaib/OPM/debug/opm-core/opm/core/io/eclipse/EclipseWriteRFTHandler.cpp:83
 #07 _ZN3Opm13EclipseWriter13writeTimeStepERKNS_23SimulatorTimerInterfaceERKNS_14SimulatorStateERKNS_9WellStateEb(..)    in /usr/include/c++/4.8/bits/basic_string.h:539
 #08 _ZN3Opm20BlackoilOutputWriter13writeTimeStepERKNS_23SimulatorTimerInterfaceERKNS_14SimulatorStateERKNS_9WellStateEb(..)    in /usr/include/c++/4.8/bits/basic_ios.h:116
 #09 _ZN3Opm13SimulatorBaseINS_30SimulatorFullyImplicitBlackoilI16UnstructuredGridEEE3runERNS_14SimulatorTimerERNS_13BlackoilStateE(..)    in /home/kaib/OPM/debug/opm-autodiff/opm/autodiff/SimulatorBase_impl.hpp:146
 #10 _ZN3Opm12FlowMainBaseINS_8FlowMainI16UnstructuredGridNS_30SimulatorFullyImplicitBlackoilIS2_EEEES2_S4_E12runSimulatorEv(..)    in /home/kaib/OPM/debug/opm-autodiff/opm/autodiff/FlowMain.hpp:597
 #11 _ZN3Opm12FlowMainBaseINS_8FlowMainI16UnstructuredGridNS_30SimulatorFullyImplicitBlackoilIS2_EEEES2_S4_E7executeEiPPc(..)    in /home/kaib/OPM/debug/opm-autodiff/opm/autodiff/FlowMain.hpp:135
 #12 main(..)                                                            in /home/kaib/OPM/debug/opm-autodiff/opm/autodiff/FlowMain.hpp:644
 #13 __libc_start_main(..)                                               in /build/buildd/eglibc-2.19/csu/libc-start.c:321
 #14 ???? 
--------------------------------------------------------------------------------

Program received signal SIGABRT, Aborted.
0x00007ffff4f10cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace 
#0  0x00007ffff4f10cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff4f140d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6b3eb4d in util_abort__ () from /usr/local/lib/x86_64-linux-gnu/libert_util.so.2
#3  0x00007ffff6b3a4e5 in hash_get () from /usr/local/lib/x86_64-linux-gnu/libert_util.so.2
#4  0x00007ffff6dd4fc3 in ecl_file_iget_named_kw () from /usr/local/lib/x86_64-linux-gnu/libecl.so.2
#5  0x00007ffff6dc63e1 in ecl_rft_node_alloc () from /usr/local/lib/x86_64-linux-gnu/libecl.so.2
#6  0x00007ffff6dc551c in ecl_rft_file_alloc () from /usr/local/lib/x86_64-linux-gnu/libecl.so.2
#7  0x00007ffff6dc5aa3 in ecl_rft_file_update () from /usr/local/lib/x86_64-linux-gnu/libecl.so.2
#8  0x0000000000db51e8 in Opm::EclipseWriterDetails::EclipseWriteRFTHandler::writeTimeStep (this=this@entry=0xa322488, filename=..., ecl_unit=ecl_unit@entry=ERT_ECL_METRIC_UNITS, simulatorTimer=..., wells=..., eclipseGrid=..., pressure=..., swat=..., sgas=...)
    at /home/kaib/OPM/debug/opm-core/opm/core/io/eclipse/EclipseWriteRFTHandler.cpp:83
#9  0x0000000000daf5a5 in Opm::EclipseWriter::writeTimeStep (this=<optimized out>, timer=..., reservoirState=..., wellState=..., isSubstep=<optimized out>) at /home/kaib/OPM/debug/opm-core/opm/core/io/eclipse/EclipseWriter.cpp:1367
#10 0x0000000000d52e3e in Opm::BlackoilOutputWriter::writeTimeStep (this=0x1710560, timer=..., localState=..., localWellState=..., substep=<optimized out>) at /home/kaib/OPM/debug/opm-autodiff/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp:283
#11 0x0000000000ccc3d0 in Opm::SimulatorBase<Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >::run (this=0x8575520, timer=..., state=...) at /home/kaib/OPM/debug/opm-autodiff/opm/autodiff/SimulatorBase_impl.hpp:143
#12 0x0000000000ccd9c0 in Opm::FlowMainBase<Opm::FlowMain<UnstructuredGrid, Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >, UnstructuredGrid, Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >::runSimulator (this=this@entry=0x7fffffffdbd0)
    at /home/kaib/OPM/debug/opm-autodiff/opm/autodiff/FlowMain.hpp:595
#13 0x0000000000cd0493 in Opm::FlowMainBase<Opm::FlowMain<UnstructuredGrid, Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >, UnstructuredGrid, Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >::execute (this=this@entry=0x7fffffffdbd0, argc=argc@entry=2, 
    argv=argv@entry=0x7fffffffde98) at /home/kaib/OPM/debug/opm-autodiff/opm/autodiff/FlowMain.hpp:135
#14 0x0000000000c439f0 in main (argc=2, argv=0x7fffffffde98) at /home/kaib/OPM/debug/opm-autodiff/examples/flow.cpp:41
(gdb) 
```

**Comment by joakim-hove** [comment]
OK - I understand roughly what is happening:

1. While saving an RFT file flow/ert first needs to load the existing RFT file on disk, and then either update the content or add a new RFT node.
2. If flow has crashed while writing this file an invalid .RFT will be left in the directory. And on the next invocation 1) will fail.

So - in this case the simple fix - is just to remove the dangling (probably broken) .RFT file from our output directory. In the longer run the ert code should handle a partly broken file. Repoening to keep tab on this.

**Comment by atgeirr** [comment]
When a new run starts, should not any existing RFT file be deleted? Is it correct to append to an existing file for a new run?

**Comment by joakim-hove** [comment]
> Is it correct to append to an existing file for a new run?

Well - it is certainly not correct to just append blindly; what we do now is to update in place - and that becomes vulnerable to broken files. Of course the simplest would be to just delete the RFT file when starting, but that will not work across restarts. If it turns out that the issue reported by @GitPaean occurs frequently we must find a more robust approach than the current.

**Comment by joakim-hove** [comment]
@GitPaean: could you send me a a version of the .RFT file creating problems; the comments about broken files certainly apply - but maybe this: https://github.com/Ensembles/ert/pull/977 actually introduced a regression.

**Comment by GitPaean** [comment]
I sent you the setup I can reproduce the problem.

**Comment by joakim-hove** [comment]
> I sent you the setup I can reproduce the problem.

OK - I have reproduced the problem; I am 99% certain that what has happened is that you have got stuck with a broken .RFT file. I have done some minor binary surgery on the file, now it works for me. I therefor suggest closing this issue now; for the future we can consider:

1. Changing the scheme for writing RFT files - e.g. just deleting the existing file at simulation start.
2. The ERT library could be more robust for broken files.

**Comment by GitPaean** [comment]
Thanks for the efforts. Closing now.
