### ISSUE TITLE
flow does not seem to produce valid UNRST files

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-autodiff#632]
at least the current master version of `flow` does not produce files which can be displayed by the latest master version of `ResInsight`:

```
make -j12 flow && ./bin/flow /home/and/src/opm-data/spe1/SPE1CASE2.DATA && ~/src/ResInsight/ApplicationCode/ResInsight --case SPE2CASE2
```

I only get this:  ![spe1-flow](https://cloud.githubusercontent.com/assets/1837735/14252021/d32663c2-fa85-11e5-8548-a791167dd875.png)

note that the issue seems to be somewhere in flow because `ebos` produces more reasonable results: ![spe1-ebos](https://cloud.githubusercontent.com/assets/1837735/14252147/4ff96250-fa86-11e5-9c65-d5cf5d5a4c05.png)

**Comment by atgeirr** [comment]
Is this also the case with your PRs applied, @andlaus?

**Comment by alfbr** [comment]
I am able to open the SPE1CASE2, but no dynamic properties are provided. Norne works as before though, so probably a fall-out from the current opm-output work.

**Comment by andlaus** [comment]
seems like this was an issue on my side: I probably switched back to master but forgot to run `make` in some of the upstream modules (oh, the joys of libraries ;)). recompiling everything from scratch fixed it. closing.

**Comment by akva2** [comment]
AHA. this is what i've been fighting on the jenkins for a while now. so it's not my issue. good.
